# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
mongodb:
  usePassword: false
  persistence:
    enabled: false
resources:
  enabled: false

config:
  managedByConfigPod:
    enabled: true
    # syncUrl: http://sdcore-adapter-v3.aether-roc.svc:8080/synchronize
  smf:
    cfgFiles:
      # https://github.com/free5gc/free5gc/blob/main/config/pcfcfg.yaml
      smfcfg.conf:
        configuration:
          mongodb:       # the mongodb connected by this PCF
            name: smf # name of the mongodb
            url: mongodb://mongodb:27017
  pcf:
    cfgFiles:
      # https://github.com/free5gc/free5gc/blob/main/config/pcfcfg.yaml
      pcfcfg.conf:
        info:
          version: 1.0.0
          description: PCF initial local configuration
        configuration:
          mongodb:       # the mongodb connected by this PCF
            name: free5gc                  # name of the mongodb
            url: mongodb://mongodb:27017
  nrf:
    cfgFiles:
      # https://github.com/free5gc/free5gc/blob/main/config/nrfcfg.yaml
      nrfcfg.conf:
        configuration:
          MongoDBName: free5gc # database name in MongoDB
          MongoDBUrl: mongodb://mongodb:27017
          #MongoDBUrl: mongodb://mongodb:27017 #works with db in omec name space
  simapp:
    cfgFiles:
      simapp.yaml:
        configuration:
          provision-network-slice: true
          sub-provision-endpt:
            addr: webui
            port: 5000
          subscribers:
          - ueId-start: 2089300007487
            ueId-end: 2089300007501
            plmnId: 20893
            opc: "981d464c7c52eb6e5036234984ad0bcf"
            op: ""
            key: "5122250214c33e723a5dd523fc145fc0"
            sequenceNumber: "16f3b3f70fc2"
          device-groups:
          - name:  "5g-gnbsim-user"
            imsis:
              - "2089300007487"
              - "2089300007488"
              - "2089300007489"
              - "2089300007490"
              - "2089300007491"
              - "2089300007492"
              - "2089300007493"
              - "2089300007494"
              - "2089300007495"
              - "2089300007496"
              - "2089300007497"
              - "2089300007498"
              - "2089300007499"
              - "2089300007500"
              - "2089300007501"
            ip-domain-name: "pool1"
            ip-domain-expanded:
              dnn: internet
              dns-primary: "8.8.8.8"
              mtu: 1460
              ue-ip-pool: "172.250.0.0/16"
            site-info: "aiab"
          network-slices:
          - name: "default"
            slice-id:
              sd: "010203"
              sst: 1
            site-device-group:
            - "5g-gnbsim-user"
            applications-information:
            - app-name: "default-app"
              end-port: 40000
              endpoint: "1.1.1.1/32"
              protocol: 17
              start-port: 40000
            deny-applications:
            - "iot-app-deny"
            permit-applications:
            - "iot-app1-permit"
            - "iot-app2-permit"
            qos:
              downlink: 20
              traffic-class: "platinum"
              uplink: 40
            site-info:
              gNodeBs:
              - name: "aiab-gnb1"
                tac: 1
              plmn:
                mcc: "208"
                mnc: "93"
              site-name: "aiab"
              upf:
                upf-name: "upf"
                upf-port: 8805
