# Copyright 2022-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Create a pod with app: mme label so that oaisim will start

apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  labels:
    app: mme
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"
