{
 "title": "AiaB Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Subscriber metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "eNodeB Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mme_number_of_enb_attached{enb_state=\"Active\", enbname=~\".+\"}) by (enbname,enbid)",
     "legendFormat": "{{ enbname }}"
    }
   ]
  },
  {
   "title": "Subscriber Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum(subscribers_info{imsi=~\".+\"}) by (imsi)"
    }
   ]
  },
  {
   "title": "UE Activation over Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Active" }
   ],
   "targets": [
    {
     "expr": "clamp_max(sum(subscribers_info{imsi=~\".+\"}) by (imsi), 1)",
     "legendFormat": "{{ imsi }}"
    }
   ]
  },
  {
   "title": "Active subscribers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum(subscribers_info{imsi=~\".+\"} > 0) by (imsi))"
    }
   ]
  },
  {
   "title": "UPF metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Current Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_latency_ns{quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_latency_ns{quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\"}[2m]))",
     "legendFormat": "Tx Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"rx\",iface=\"Core\"}[2m]))",
     "legendFormat": "Rx Bitrate"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(upf_jitter_ns{quantile=\"90\"})",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "sum(upf_jitter_ns{quantile=\"99.9\"})",
     "legendFormat": "99.9th percentile"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(upf_dropped_count[2m]))",
     "legendFormat": "Packet drops per second"
    }
   ]
  }
 ]
}