apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mme
  namespace: omec
spec:
  endpoints:
    - path: /metrics
      port: prometheus-exporter
  namespaceSelector:
    matchNames:
      - omec
  selector:
    matchLabels:
      app: mme
