apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mme
  namespace: omec
spec:
  endpoints:
    - path: /metrics
      port: metrics3081
  namespaceSelector:
    matchNames:
      - omec
  selector:
    matchLabels:
      app.kubernetes.io/name: mme-metrics
