{
 "title": "AIAB_5g Copy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "5G Active PDU Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smf_pdu_sessions" }
   ]
  },
  {
   "title": "UPF Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nf_status{nfType=\"UPF\"}",
     "legendFormat": "{{ Nfname }}"
    }
   ]
  },
  {
   "title": "gNodeB Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nf_status{nfType=\"GNB\"}",
     "legendFormat": "{{ Nfname }}"
    }
   ]
  },
  {
   "title": "5G Core Subscribers",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(core_subscriber{state=\"Connected\"}) by (imsi, slice)"
    }
   ]
  },
  {
   "title": "UPF Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Core\"}[2m]))",
     "legendFormat": "Upstream Bitrate"
    },
    {
     "expr": "sum(8 * irate(upf_bytes_count{dir=\"tx\",iface=\"Access\"}[2m]))",
     "legendFormat": "Downstream Bitrate"
    }
   ]
  },
  {
   "title": "SMF Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(smf_svc_stats) by (msgtype)",
     "legendFormat": "{{ msgtype }}"
    }
   ]
  }
 ]
}